object CheckCommand "cloud_gcp" {
    command = [ PluginContribDir + "/check_cloud_gcp" ]

    arguments = {
        "--json-file" = {
            value = "$cloud_gcp_json_file$"
            description = "GCP service account key file"
        }
        "--ignore-api-warning" = {
            value = "$cloud_gcp_ignore_api_warning$"
            description = "Disables warning when querying without a zone filter (please do not do that)"
        }
        "--zone" = {
            value = "$cloud_gcp_zone$"
            description = "GCP Zone name, can include wildcards"
        }
        "--filter" = {
            value =  "$cloud_gcp_filter$"
            description = "Filter expression that filters resources"
        }
        "compute" = {
            value = "$cloud_gcp_compute$"
            order = 1
            description = "Checks in the Compute Engine context"
        }
        "instance" = {
            value = "$cloud_gcp_instance$"
            order = 2
            description = "Checks a single GCP instance"
        }
        "instances" = {
            value = "$cloud_gcp_instances$"
            order = 2
            description = "Checks multiple GCP instances"
        }
    }
}
