run:
  timeout: 5m
  skip-files:
    - '(.+)_test\.go'

linters:
  disable-all: false
  enable:
    - funlen
    - dogsled
    - dupl
    - whitespace
    - wsl
    - exportloopref
  disable:
    - scopelint
    - bodyclose
    - contextcheck
    - nilerr
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - unparam
    - musttag
  presets:
    - bugs
    - unused
  fast: false
