run:
  timeout: 5m

issues:
  exclude-files:
    - '(.+)_test\.go'

linters:
  disable-all: false
  disable:
    - bodyclose
    - contextcheck
    - nilerr
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - unparam
    - musttag
  presets:
    - bugs
    - unused
  fast: false
